### ISSUE TITLE
Videos fetched from playlist is inconsistent

### ISSUE THREAD

**Issue by Spimy** [jasonhaxstuff/popyt#139]
As the title suggests, when I fetch videos from a playlist, the order of the videos is always different.
e.g:
![image](https://user-images.githubusercontent.com/34989646/85201387-f1c01480-b30f-11ea-8900-475f433ca3ee.png)
![image](https://user-images.githubusercontent.com/34989646/85201409-11efd380-b310-11ea-8ca3-40c712ae34e1.png)

**Comment by jasonhaxstuff** [comment]
Fixed in commit 29db495 and version [v4.1.0](https://www.npmjs.com/package/popyt/v/4.1.0).
Happy coding!

**Comment by Spimy** [comment]
I have updated to v4.1.0 but it is still randomised and isn't consisten
![image](https://user-images.githubusercontent.com/34989646/85208367-d5889b80-b340-11ea-82f9-7319a9f4ec03.png)

**Comment by jasonhaxstuff** [comment]
This is now an issue with your code, specifically [these lines](https://github.com/Spimy/muse-cli/blob/master/src/templates/typescript/src/commands/music/play.ts#L70-L75). You shouldn't use `forEach`, since it doesn't retain the order of an array. Instead use a for loop that loops through each index of the array, like I do [here](https://github.com/jasonhaxstuff/popyt/commit/29db495f4e05d345c249c04140f18cf3a95fff8f#diff-5c7865dde4a1f6e0d8116584d8f4e62eR182).

**Comment by Spimy** [comment]
I was about to edit and mention I did just that and it's now all good, thanks 😁
