### ISSUE TITLE
Error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential

### ISSUE THREAD

**Issue by rawalprashant** [jasonhaxstuff/popyt#475]
Hi,

I am getting the following error when I tried to call function

const youtube = new YouTube(process.env.YOUTUBE_API_KEY, { cache: false })
const YTCategories = await youtube.getCategories()
console.log(process.env.YTCategories);

Error: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at IncomingMessage.<anonymous> (D:\xampp\htdocs\nextjs-prisma-devcomm\node_modules\popyt\out\util\request.js:148:39)

Can you please help me to resolve this asap?

Thanks,

**Comment by jasonhaxstuff** [comment]
The following test code still works perfectly when ran: https://github.com/jasonhaxstuff/popyt/blob/master/test/video-category.spec.ts
Therefore I have to come to the conclusion that you are not properly setting your YouTube API key.

**Comment by rawalprashant** [comment]
@jasonhaxstuff 

Hi, Can you please take moment to answer my above queries? it helps me to move on with my current work.

Thanks

**Comment by jasonhaxstuff** [comment]
It returns an array of VideoCategory objects. These are possible categories for YouTube videos to be classified under. Your token is part of this data because each entity in the wrapper has a `youtube` property that is the original `YouTube` object that created it, which includes a token. It is just a native JavaScript array, so loop through it as you would any other array.

**Comment by rawalprashant** [comment]
@jasonhaxstuff Ok, that makes sense, thank you for valuable response :)
